import{S as f,i as l}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function m(s){const r="https://pixabay.com/api/",o="43436630-0ca2cab0bed204149ca1c5fee",i=new URLSearchParams({key:o,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${r}?${i}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function p(s){return s.map(({webformatURL:r,largeImageURL:o,tags:i,likes:e,views:t,comments:n,downloads:u})=>`
     <a class="gallery-link" href="${o}">
                <img class="gallery-img" src="${r}" alt="${i}" />
                <ul class="search-list">
                    <li class="info"><span class="info-item">Likes </span>${e}</li>
                    <li class="info"><span class="info-item">Views </span>${t}</li>
                    <li class="info"><span class="info-item">Comments </span>${n}</li>
                    <li class="info"><span class="info-item">Downloads </span>${u}</li>
                </ul>
            </a>


    `).join()}const c=document.querySelector(".search-form"),d=document.querySelector(".gallery"),a=document.querySelector(".loader");c.addEventListener("submit",y);a.style.display="none";const h=new f(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){s.preventDefault(),a.style.display="inline-block";const{search:r}=s.currentTarget.elements;if(r.value===""){l.show({title:"error",titleColor:"white",message:"Please find what you want to find",messageColor:"white",color:"red",position:"topCenter",timeout:"2000"});return}m(r.value).then(o=>{if(a.style.display="none",d.innerHTML=p(o.hits),h.refresh(),o.total===0){l.show({title:"error",titleColor:"white",message:"We cannot find a picture for this name, please enter the correct name",messageColor:"white",color:"red",position:"topCenter",timeout:"2000"}),c.reset();return}}).catch(o=>l.show({title:"error",titleColor:"white",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",color:"red",position:"topCenter",timeout:"2000"}).finally(()=>{a.style.display="none"}))}
//# sourceMappingURL=commonHelpers.js.map
